# Generated by Django 5.0 on 2024-03-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='writer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
