# Generated by Django 5.0 on 2024-05-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='diploma',
        ),
    ]
