# Generated by Django 5.0 on 2024-05-07 02:40

import datetime
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_remove_student_diploma'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Myfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fileName', models.FileField(upload_to='photos/')),
                ('school', models.CharField(choices=[('lmc', 'LMC'), ('sfc', 'SFC'), ('cms', 'CMS'), ('mbic', 'MBIC')], default='CMS', max_length=6)),
                ('grade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=4)),
                ('subject', models.CharField(choices=[('English', 'Eng'), ('Hindi', 'Hin'), ('Mathematics', 'Maths'), ('Computer', 'Comp')], default='English', max_length=20)),
                ('type', models.CharField(choices=[('Classwork', 'CW'), ('Homework', 'HW')], default='HW', max_length=10)),
                ('dateOfAssignment', models.DateField(default=datetime.date.today)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
