# Generated by Django 5.0.6 on 2024-07-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_myfiles_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfiles',
            name='fileName',
            field=models.FileField(upload_to='raw/'),
        ),
    ]
