# Generated by Django 5.0 on 2024-04-29 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='dateOfAssignment',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='photo',
            name='subject',
            field=models.CharField(choices=[('English', 'Eng'), ('Hindi', 'Hin'), ('Mathematics', 'Maths'), ('Computer', 'Comp')], default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='photo',
            name='type',
            field=models.CharField(choices=[('Classwork', 'CW'), ('Homework', 'HW')], default='HW', max_length=10),
        ),
    ]
