# Generated by Django 5.0 on 2024-03-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusText', models.CharField(max_length=200)),
                ('statusDate', models.DateTimeField()),
            ],
        ),
    ]
